# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VIO_alignment_Tool(object):
    def setupUi(self, VIO_alignment_Tool):
        VIO_alignment_Tool.setObjectName("VIO_alignment_Tool")
        VIO_alignment_Tool.resize(789, 896)
        VIO_alignment_Tool.setMinimumSize(QtCore.QSize(709, 577))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        VIO_alignment_Tool.setFont(font)
        VIO_alignment_Tool.setMouseTracking(False)
        VIO_alignment_Tool.setWindowOpacity(1.0)
        VIO_alignment_Tool.setAutoFillBackground(True)
        VIO_alignment_Tool.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(VIO_alignment_Tool)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.offset_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.offset_spinbox.setMaximum(10000)
        self.offset_spinbox.setObjectName("offset_spinbox")
        self.gridLayout.addWidget(self.offset_spinbox, 8, 3, 1, 1)
        self.Start_from = QtWidgets.QSlider(self.centralwidget)
        self.Start_from.setMaximum(100)
        self.Start_from.setPageStep(1)
        self.Start_from.setOrientation(QtCore.Qt.Horizontal)
        self.Start_from.setObjectName("Start_from")
        self.gridLayout.addWidget(self.Start_from, 11, 1, 1, 1)
        self.GT_file = QtWidgets.QPushButton(self.centralwidget)
        self.GT_file.setObjectName("GT_file")
        self.gridLayout.addWidget(self.GT_file, 2, 2, 1, 1)
        self.gt_shifter = QtWidgets.QSlider(self.centralwidget)
        self.gt_shifter.setMinimumSize(QtCore.QSize(200, 0))
        self.gt_shifter.setMaximumSize(QtCore.QSize(300, 16777215))
        self.gt_shifter.setPageStep(1)
        self.gt_shifter.setOrientation(QtCore.Qt.Horizontal)
        self.gt_shifter.setObjectName("gt_shifter")
        self.gridLayout.addWidget(self.gt_shifter, 9, 2, 1, 2)
        self.xscale_spinbox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.xscale_spinbox.setDecimals(4)
        self.xscale_spinbox.setMaximum(100.0)
        self.xscale_spinbox.setSingleStep(0.1)
        self.xscale_spinbox.setProperty("value", 1.0)
        self.xscale_spinbox.setObjectName("xscale_spinbox")
        self.gridLayout.addWidget(self.xscale_spinbox, 4, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 11, 0, 1, 1)
        self.VIO_file = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VIO_file.sizePolicy().hasHeightForWidth())
        self.VIO_file.setSizePolicy(sizePolicy)
        self.VIO_file.setObjectName("VIO_file")
        self.gridLayout.addWidget(self.VIO_file, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 2, 1, 1)
        self.save_result = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_result.sizePolicy().hasHeightForWidth())
        self.save_result.setSizePolicy(sizePolicy)
        self.save_result.setObjectName("save_result")
        self.gridLayout.addWidget(self.save_result, 11, 2, 2, 2)
        self.range_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.range_spinbox.setMaximum(10000)
        self.range_spinbox.setProperty("value", 1)
        self.range_spinbox.setObjectName("range_spinbox")
        self.gridLayout.addWidget(self.range_spinbox, 5, 3, 1, 1)
        self.nav_offset_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.nav_offset_spinbox.setProperty("value", 0)
        self.nav_offset_spinbox.setObjectName("nav_offset_spinbox")
        self.gridLayout.addWidget(self.nav_offset_spinbox, 6, 3, 1, 1)
        self.yscale_spinbox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.yscale_spinbox.setDecimals(4)
        self.yscale_spinbox.setMinimum(0.0)
        self.yscale_spinbox.setMaximum(100.0)
        self.yscale_spinbox.setSingleStep(0.1)
        self.yscale_spinbox.setProperty("value", 1.0)
        self.yscale_spinbox.setObjectName("yscale_spinbox")
        self.gridLayout.addWidget(self.yscale_spinbox, 3, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.Zangle_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zangle_spinbox.sizePolicy().hasHeightForWidth())
        self.Zangle_spinbox.setSizePolicy(sizePolicy)
        self.Zangle_spinbox.setMinimum(-360)
        self.Zangle_spinbox.setMaximum(360)
        self.Zangle_spinbox.setObjectName("Zangle_spinbox")
        self.horizontalLayout_2.addWidget(self.Zangle_spinbox)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.Yangle_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Yangle_spinbox.sizePolicy().hasHeightForWidth())
        self.Yangle_spinbox.setSizePolicy(sizePolicy)
        self.Yangle_spinbox.setMinimum(-360)
        self.Yangle_spinbox.setMaximum(360)
        self.Yangle_spinbox.setObjectName("Yangle_spinbox")
        self.horizontalLayout_2.addWidget(self.Yangle_spinbox)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.Xangle_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Xangle_spinbox.sizePolicy().hasHeightForWidth())
        self.Xangle_spinbox.setSizePolicy(sizePolicy)
        self.Xangle_spinbox.setMinimum(-360)
        self.Xangle_spinbox.setMaximum(360)
        self.Xangle_spinbox.setObjectName("Xangle_spinbox")
        self.horizontalLayout_2.addWidget(self.Xangle_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 2, 1, 1)
        self.End_to = QtWidgets.QSlider(self.centralwidget)
        self.End_to.setMaximum(100)
        self.End_to.setPageStep(1)
        self.End_to.setOrientation(QtCore.Qt.Horizontal)
        self.End_to.setInvertedAppearance(True)
        self.End_to.setObjectName("End_to")
        self.gridLayout.addWidget(self.End_to, 12, 1, 1, 1)
        self.vio_shifter = QtWidgets.QSlider(self.centralwidget)
        self.vio_shifter.setMinimumSize(QtCore.QSize(200, 0))
        self.vio_shifter.setMaximumSize(QtCore.QSize(300, 16777215))
        self.vio_shifter.setPageStep(1)
        self.vio_shifter.setOrientation(QtCore.Qt.Horizontal)
        self.vio_shifter.setObjectName("vio_shifter")
        self.gridLayout.addWidget(self.vio_shifter, 7, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 12, 0, 1, 1)
        self.canvas_layout = QtWidgets.QGridLayout()
        self.canvas_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.canvas_layout.setObjectName("canvas_layout")
        self.gridLayout.addLayout(self.canvas_layout, 2, 0, 8, 2)
        self.canvas_3d_layout = QtWidgets.QGridLayout()
        self.canvas_3d_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.canvas_3d_layout.setObjectName("canvas_3d_layout")
        self.gridLayout.addLayout(self.canvas_3d_layout, 0, 0, 1, 4)
        VIO_alignment_Tool.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VIO_alignment_Tool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        VIO_alignment_Tool.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(VIO_alignment_Tool)
        self.statusBar.setObjectName("statusBar")
        VIO_alignment_Tool.setStatusBar(self.statusBar)

        self.retranslateUi(VIO_alignment_Tool)
        QtCore.QMetaObject.connectSlotsByName(VIO_alignment_Tool)

    def retranslateUi(self, VIO_alignment_Tool):
        _translate = QtCore.QCoreApplication.translate
        VIO_alignment_Tool.setWindowTitle(_translate("VIO_alignment_Tool", "VIO_alignment_Tool"))
        self.GT_file.setText(_translate("VIO_alignment_Tool", "Open GT file"))
        self.label_6.setText(_translate("VIO_alignment_Tool", "Shift GT data"))
        self.label_3.setText(_translate("VIO_alignment_Tool", "Start From"))
        self.VIO_file.setText(_translate("VIO_alignment_Tool", "Open VIO path"))
        self.label_4.setText(_translate("VIO_alignment_Tool", "Show range"))
        self.save_result.setText(_translate("VIO_alignment_Tool", "Save Result"))
        self.label_8.setText(_translate("VIO_alignment_Tool", "Z"))
        self.label_9.setText(_translate("VIO_alignment_Tool", "Y"))
        self.label_10.setText(_translate("VIO_alignment_Tool", "X"))
        self.label_2.setText(_translate("VIO_alignment_Tool", "Y_scale"))
        self.label_5.setText(_translate("VIO_alignment_Tool", "Shift VIO data"))
        self.label.setText(_translate("VIO_alignment_Tool", "X scale"))
        self.label_7.setText(_translate("VIO_alignment_Tool", "End To"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VIO_alignment_Tool = QtWidgets.QMainWindow()
    ui = Ui_VIO_alignment_Tool()
    ui.setupUi(VIO_alignment_Tool)
    VIO_alignment_Tool.show()
    sys.exit(app.exec_())
